source "https://rubygems.org"

gem 'jekyll', '3.8.5'
gem 'jekyll-sitemap'
gem 'jekyll-redirect-from'
gem 'jekyll-last-modified-at'
gem 'octopress', '~> 3.0'
gem 'redcarpet'
gem 'rake'
gem 'gemoji'
gem 'therubyracer'
gem 'nokogiri'
gem 'git'
gem 'metainspector'
gem 'mini_magick'
