apiVersion: extensions/v1beta1
kind: NetworkPolicy
metadata:
  name: docs-server-access
  namespace: {{ kubernetes_namespace }}
spec:
  podSelector:
    matchLabels:
      app: docs-server
  ingress:
    - ports:
      - protocol: TCP
        port: 4000